export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const SET_AUTHOR_FILTER = 'SET_AUTHOR_FILTER';
export const SET_TITLE_FILTER = 'SET_TITLE_FILTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
